config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :turtles
    post 'difficulty/:id/:difficulty', to: 'turtles#difficulty'
    #options 'turtles', action: :options
    match 'turtles', to: 'turtles#options', via: [:options,]
  end

  get 'turtles/list', to: 'turtles#list'
  get 'turtles/import', to: 'turtles#import'
  get 'turtles/importme', to: 'turtles#importme'
  get 'turtles/delete_index', to: 'turtles#delete_index'
  resources :turtles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/turtle.rb
class Turtle < ApplicationRecord
  validates :left, presence: true,
                   length: { minimum: 2 }
end

app/controllers/api/turtles_controller.rb
class Api::TurtlesController < ApiController
  after_action :set_version_header

  def index
    if params[:index] == "Alle" || params[:index].blank?
      render json: @turtles = Turtle.all.shuffle
    else
      render json: @turtles = Turtle.where(:index=>params[:index]).shuffle
    end
  end

  def show
    render json: @turtle
  end

  def create
    if params[:index].blank?
      @turtle = Turtle.new(turtle_params.merge(index: "Alle"))
    else
      @turtle = Turtle.new(turtle_params)
    end
    @turtle.save
    render json: @turtle
  end

  def difficulty
    @turtle = Turtle.find(params[:id])
    @turtle[:difficulty] = params[:difficulty]
    @turtle.save
  end

  def destroy
    @turtle = Turtle.find(params[:id])
    @turtle.destroy
  end

  def options
  end

  private
    def turtle_params
      params.require(:turtle).permit(:left, :right, :index, :difficulty)
      #params.permit(:left, :right, :index, :difficulty)
    end

  protected
    def set_version_header
        response.headers['Access-Control-Allow-Origin'] = 'https://quickdict.og8.org'
        response.headers['Access-Control-Allow-Methods'] = 'POST, OPTIONS'
        response.headers['Access-Control-Allow-Headers'] = '*, X-Requested-With, X-Prototype-Version, X-CSRF-Token, Content-Type'
    end

end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/turtles_controller.rb
class TurtlesController < ApplicationController
  after_action :set_version_header

  def index
    @turtles = Turtle.all
    @index = params[:index]
    @indexe = Turtle.select(:index).where.not(index: "Alle").distinct
  end

  def show
    @turtle = Turtle.find(params[:id])
  end

  def new
    @turtle = Turtle.new()
    @index = params[:index]
  end

  def edit
    @turtle = Turtle.find(params[:id])
  end

  def create
    if params[:turtle][:index].blank?
      @turtle = Turtle.new(turtle_params.merge(index: "Alle"))
    else
      @turtle = Turtle.new(turtle_params)
    end
    if @turtle.save
      redirect_to action: :new, index: turtle_params[:index]
    else
      render 'new'
    end
  end

  def update
    @turtle = Turtle.find(params[:id])
 
    if @turtle.update(turtle_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @turtle = Turtle.find(params[:id])
    @turtle.destroy

    redirect_to action: :list
  end

  def list
    @indexe = Turtle.select(:index).where.not(index: "Alle").distinct
    @turtles = Turtle.all
  end

  def import
  end

  def importme
    url = params[:url]
    inverted = params[:invert]
    if url.start_with?("https://my.dict.cc/print/")
      TurtlesHelper::Parser.new.parse(url, inverted)
    end
    redirect_to action: "list"
  end

  def delete_index
    Turtle.where(index: params[:index]).destroy_all
    redirect_to action: 'list'
  end

  private
    def turtle_params
      params.require(:turtle).permit(:left, :right, :index, :difficulty)
    end

  protected
    def set_version_header
        response.headers['Access-Control-Allow-Origin'] = 'https://quickdict.og8.org https://xt.og8.org'
        response.headers['Access-Control-Allow-Methods'] = 'POST, OPTIONS'
        response.headers['Access-Control-Allow-Headers'] = '*, X-Requested-With, X-Prototype-Version, X-CSRF-Token, Content-Type'
        response.headers['X-Frame-Options'] = 'ALLOW-FROM xt.og8.org'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/turtles_helper.rb
require 'open-uri'
require 'nokogiri'

module TurtlesHelper

  class Parser

    def parse(url, inverted)

      doc = Nokogiri::HTML(open(url))

      tab = doc.search('table')[1]

      trlist = tab.xpath('tr')

      index = trlist[0].xpath("td")[0].content

      trlist[2..-1].each do |tr|
        td = tr.xpath("td")
        turtle = Turtle.new
        turtle.index = index
        if inverted
          turtle.left = td[1].content
          turtle.right = td[0].content
        else
          turtle.left = td[0].content
          turtle.right = td[1].content
        end
        turtle.difficulty = 1
        turtle.save()

      end

    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turtles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/turtles/_form.html.erb
<script type="text/javascript" src="<%= Rails.public_path.join('/js/turtles.js') %>"></script>

<center>
<div id="all">
<div id="container">
<%= form_with model: @turtle, local: true do |form| %>
  <div id="inner">
    <%= link_to turtles_path, method: :get do %>
      <div id="qm" class='arrow left'>
      </div>
    <% end %>
    <%= form.submit "", id:'plus', class:'arrow right btn-trans' %>
    <%= form.text_area :left, class:"boxes qmbox", id:"box1" %>
    <%= form.text_area :right, class:"boxes qmbox", id:"box2" %>
    <div>
      <div class="difficulty" id="leicht" onclick="clickdiff(0,true)">
        Leicht
      </div>
      <div class="difficulty" id="ok" onclick="clickdiff(1,true)">
        OK
      </div>
      <div class="difficulty" id="schwer" onclick="clickdiff(2,true)">
        Schwer
      </div>
      <span class="little-margin">
        <%= form.label :index %>:
        <%= form.text_field :index, value:(defined?@index)?@index:@turtle[:index], class:"textin", id:"editindex" %>
      </span>
    </div>
    <%= form.text_field :difficulty, value:@turtle[:difficulty], class:"invisible", id:"difficulty" %>
  </div>
<% end %>
</div>
</div>
</center>

app/views/turtles/edit.html.erb
 
<%= render 'form' %>
 

app/views/turtles/import.html.erb
<center>
  <%= link_to turtles_path, method: :get do %>
    <div id="qm" class="arrow" style="position: relative">
    </div>
  <% end %>
  <br>
<div class="listtable">

  <%= link_to "dict.cc Vocab Lists", "https://my.dict.cc/lists/?f=-inlist-DEEN", method: :get %>
  <br>

  <%= form_with(url: "importme", method:"get", local:true) do |form| %>
    <%= form.text_area :url, class:"boxes qmbox", id:"box1" %>
    <br>
    <span class="difficulty">
      <%= check_box_tag "invert" %>
      <%= label_tag "Invert", "Invertiert" %>
    </span>
    <%= form.submit "Importieren", id:'', class:"difficulty submit" %>
  </div>
<% end %>

</div>

</center>

app/views/turtles/index.html.erb
<script src="/js/turtles.js"></script>
<script>
  window.addEventListener('load', function(){ loadnext(); });
</script>
 
<%= content_tag :div, id: "temp_information", data: {turtles: @turtles, index: @index} do %>
<% end %>

<center>
<div id="all">
<div id="container">
  <div id="inner">
    <div id="prev" class='arrow' onclick="prev()">
    </div>
    <div id="next" class='arrow' onclick="next()">
    </div>
    <div id="box1" class="boxes">
    </div>
    <div id="box2" class="boxes" onclick="toggle()">
    </div>
    <div class="difficulty" id="leicht" onclick="clickdiff(0)">
      Leicht
    </div>
    <div class="difficulty" id="ok" onclick="clickdiff(1)">
      OK
    </div>
    <div class="difficulty" id="schwer" onclick="clickdiff(2)">
      Schwer
    </div>
    <div class="difficulty" id="index" onclick="toggle_index()">
    </div>
    <%= link_to turtles_list_path, method: :get do %>
      <div class="difficulty" id="list">
      </div>
    <% end %>
    <div class="difficulty" id="minus" onclick="delme()">
    </div>
    <div class="difficulty" id="edit" onclick="editme()">
    </div>
    <%= link_to new_turtle_path, method: :get do %>
      <div class="difficulty" id="plus">
      </div>
    <% end %>
    </a>

    <div id="divindex">
      <%= link_to turtles_path(index: "Alle"), method: :get do %>
        <div class="difficulty">Alle</div>
      <% end %>
      <% @indexe.each do |index| %>
      <%= link_to turtles_path(index: index.index), method: :get do %>
        <% if index.index == @index %>
          <div class="difficulty selected"><%= index.index %>
        <% else %>
          <div class="difficulty"><%= index.index %>
        <% end %>
        </div>
      <% end %>
      <% end %>
      <%= link_to turtles_import_path, method: :get do %>
        <div class="difficulty" id="import"></div>
      <% end %>
    </div>
  </div>
</div>
</div>
</center>

app/views/turtles/list.html.erb
<center>
  <%= link_to turtles_path, method: :get do %>
    <div id="qm" class="arrow" style="position: relative">
    </div>
  <% end %>
  <br>
<table class="listtable">
  <tr>
    <th>Index</th>
  </tr>
  <% @indexe.each do |index| %>
    <tr>
      <td><%= index.index %></td>
      <td><%= link_to image_tag("delete.png", height:"15px"), turtles_delete_index_path(:index => index.index) %></td>
    </tr>
  <% end %>
</table>

<table class="listtable">
  <tr>
    <th>Vorderseite</th>
    <th>Rückseite</th>
    <th>Index</th>
    <th colspan="3"></th>
  </tr>

  <% @turtles.each do |turtle| %>
    <tr>
      <td><%= turtle.left %></td>
      <td><%= turtle.right %></td>
      <td><%= turtle.index %></td>
      <td><%= link_to image_tag("lupe.png", height:"15px"), turtle_path(turtle) %></td>
      <td><%= link_to image_tag("edit.png", height:"15px"), edit_turtle_path(turtle) %></td>
      <td><%= link_to image_tag("delete.png", height:"15px"), turtle_path(turtle), method: "delete" %></td>
    </tr>
  <% end %>
</table>

</center>

app/views/turtles/new.html.erb
<%= render 'form' %>

app/views/turtles/show.html.erb
<p>
  <strong>Left:</strong>
  <%= @turtle.left %>
</p>
 
<p>
  <strong>Right:</strong>
  <%= @turtle.right %>
</p>

<%= link_to 'Back', turtles_path %>